datasets: 'caption_mimic'

# set pretrained as a file path or an url
pretrained: './checkpoint.pth'
#pretrained: False


# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 16
init_lr: 1e-4

image_size: 224
# generation configs
tokenizer_max_length: 100
max_length: 100
min_length: 5
num_beams: 3
prompt: ''

# optimizer
weight_decay: 0.02
min_lr: 1e-5
max_epoch: 30
