datasets: 'caption_mimic'

# set pretrained as a file path or an url
pretrained: './checkpoint.pth'
#pretrained: False

#pretrained: False

# size of vit model; base or large
init_lr: 1e-4

# vit: 'large'
# vit_grad_ckpt: True
# vit_ckpt_layer: 5
# batch_size: 16
# init_lr: 2e-6

image_size: 224
#image_size: 384

# generation configs
tokenizer_max_length: 100
max_length: 100
min_length: 5
num_beams: 3
prompt: ''

# optimizer
weight_decay: 0.02
min_lr: 1e-5
max_epoch: 30